language: python
python:
  - "3.7"

services:
  - docker

install:
  - pip install -r requeriments.txt

before_script:
  - python manage.py migrate
  - pip install docker-compose

script:
  - docker-compose run app sh -c "python manage.py test "
