language: python
python:
  - "3.7"

services:
  - docker

install:
  - pip install -r requeriments.txt

before_script:
  - python3 manage.py makemigrations
  - python3 manage.py migrate

script:
  - python3 manage.py test"
