version: "3"

services:
  web:
    build: .

    container_name: booklist

    restart: unless-stopped

    env_file:
      - .env

    ports:
      - "8000:8000"

    command: sh./docker-booklist-app-commands.sh
