version: "3"

services:

    web:

        build: .

        container_name: booklist-app

        restart: unless-stopped

        env_file:

            - .env

        ports:

            - "80:${DJANGO_PORT}"

        command: python3 manage.py runserver
