version: "3"

services:
  web:
    build: .

    container_name: booklist

    restart: unless-stopped

    env_file:
      - .env

    ports:
      - "80:8000"

    command: python3 manage.py runserver
